spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ToDo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Mht-9769099

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.data.jpa: DEBUG
    org.springframework.security: INFO

jwt:
  get:
    token:
      uri: /authenticate
