# DataSource Configuration
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:9898/ToDo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Mht-9769099
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: todo-task-management-430822:us-central1:todo-task-management-database
        enableIamAuth: true
        sslmode: disable

# JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Application Configuration
  main:
    allow-bean-definition-overriding: true

# Logging Configuration
logging:
  level:
    org.springframework.data.jpa: DEBUG
    org.springframework.security: INFO

# Server Configuration
server:
  port: 8000

# JWT Configuration
jwt:
  get:
    token:
      uri: /authenticate

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: '*'
